#!/usr/bin/env bash
set -euo pipefail

DOCKERFILE="$(cd "$(dirname "$0")/.." && pwd)/Dockerfile"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ATTRIBUTES="$REPO_ROOT/.gitattributes"
PRODUCER_SOURCE="$REPO_ROOT/v2/pkg/github/visualhive_pull_request_bundle.go"

producer_commit="$(sed -nE 's/^const VisualHivePullRequestProducerCommit = "([a-f0-9]{40})"$/\1/p' "$PRODUCER_SOURCE")"
docker_commit="$(sed -nE 's/^ARG VISUAL_HIVE_REF=([a-f0-9]{40})$/\1/p' "$DOCKERFILE")"
test -n "$producer_commit"
test "$docker_commit" = "$producer_commit"

grep -Fq 'bash bubblewrap curl' "$DOCKERFILE"
grep -Fq 'curl procps bzip2' "$DOCKERFILE"
grep -Fq 'test -x /usr/bin/ps' "$DOCKERFILE"
grep -Eq '^ARG CODEX_VERSION=[0-9]+\.[0-9]+\.[0-9]+$' "$DOCKERFILE"
grep -Fq 'npm install -g @openai/codex@${CODEX_VERSION}' "$DOCKERFILE"
grep -Fq 'test -f /opt/hive/codex/bin/codex' "$DOCKERFILE"
grep -Fq 'chmod 0555 /opt/hive/codex/bin/codex' "$DOCKERFILE"
grep -Fq 'ENV PATH="/opt/hive/codex/bin:${PATH}"' "$DOCKERFILE"
grep -Eq '^FROM node:22\.23\.1-bookworm-slim@sha256:[0-9a-f]{64} AS visual-hive-builder$' "$DOCKERFILE"
grep -Fq 'git fetch --depth=1 origin "$VISUAL_HIVE_REF"' "$DOCKERFILE"
grep -Fq 'test "$(git rev-parse HEAD)" = "$VISUAL_HIVE_REF"' "$DOCKERFILE"
grep -Fq 'node scripts/build-release-bundle.mjs --output /visual-hive-release' "$DOCKERFILE"
grep -Fq 'COPY --from=visual-hive-builder /visual-hive-release /opt/hive/visual-hive' "$DOCKERFILE"
grep -Fq 'ENV HIVE_VISUAL_HIVE_HOME=/opt/hive/visual-hive' "$DOCKERFILE"
grep -Fq 'chmod -R a-w /opt/hive/visual-hive' "$DOCKERFILE"
grep -Fq 'node /opt/hive/visual-hive/visual-hive.mjs --version' "$DOCKERFILE"
grep -Fq 'find /opt/hive/dashboard /tmp/hive/bin -type f -name '\''*.sh'\'' -print' "$DOCKERFILE"
grep -Fq 'runtime_shebang_files=' "$DOCKERFILE"
grep -Fq '/tmp/hive/bin/nous-sync.py /tmp/hive/bin/nous-hive-gate.py' "$DOCKERFILE"
grep -Fq '/opt/hive/dashboard/agent-activity.py /opt/hive/dashboard/build-snapshot.mjs' "$DOCKERFILE"
grep -Fq 'runtime_text_files="$runtime_shebang_files /usr/local/etc/hive/backends.conf"' "$DOCKERFILE"
grep -Fq "sed -i 's/\\r\$//' \"\$runtime_file\"" "$DOCKERFILE"
grep -Fq 'test "$(head -c 2 "$script")" = '\''#!'\''' "$DOCKERFILE"
grep -Fq 'chmod 0555 $runtime_shebang_files' "$DOCKERFILE"
grep -Fq 'carriage return remains in runtime text file' "$DOCKERFILE"
grep -Fqx '*.sh text eol=lf' "$ATTRIBUTES"
grep -Fqx '*.py text eol=lf' "$ATTRIBUTES"
grep -Fqx '*.mjs text eol=lf' "$ATTRIBUTES"
grep -Fqx 'config/backends.conf text eol=lf' "$ATTRIBUTES"

echo "Dockerfile contains the contained Visual Hive runtime and LF text prerequisites."
