package hostedstatus

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	gh "github.com/google/go-github/v72/github"

	"github.com/kubestellar/hive/pkg/integrated"
)

// ErrOperationRunNotFound means exhaustive bounded discovery found no exact
// queued, active, or completed run for a persisted request. Callers may
// redispatch only the identical unexpired bytes after rechecking state heads.
var ErrOperationRunNotFound = errors.New("hosted operation dispatch has no exact queued, active, or completed workflow run")

// ErrOperationRunTerminatedWithoutReceipt means the exact immutable managed
// workflow run reached a terminal state but its bounded result artifact could
// not be verified. Callers must obtain a fresh authoritative status receipt
// proving the exact durable request binding before redispatching identical
// bytes; this error alone never grants retry authority.
var ErrOperationRunTerminatedWithoutReceipt = errors.New("exact hosted operation run terminated without a verifiable result receipt")

// OperationResult is the exact provenance-bound result of one public hosted
// operator command. Failure receipts are returned with Error populated so the
// public CLI can emit one useful JSON document while preserving a nonzero exit.
type OperationResult struct {
	StateReceiptEvidence
	Conclusion string `json:"conclusion"`
	Error      string `json:"error,omitempty"`
}

// WaitForOperation waits only for the workflow run whose generated display
// title contains the exact operation and idempotency key. It never accepts a
// different recent run as the requested result.
func WaitForOperation(ctx context.Context, client *gh.Client, config integrated.Config, operation, requestID, requestSHA256 string, issuedAt time.Time) (OperationResult, error) {
	return waitForExactOperation(ctx, client, config, operation, requestID, requestSHA256, "control", "", issuedAt)
}

// WaitForControllerOperation waits for an ordinary cycle, pause, or resume
// request. These operations are idempotent through the legacy controller
// ledger and intentionally carry no human-operator digest or actor authority.
func WaitForControllerOperation(ctx context.Context, client *gh.Client, config integrated.Config, operation, requestID, expectedHeadSHA string, issuedAt time.Time) (OperationResult, error) {
	expectedJob := "control"
	if operation == "cycle" {
		expectedJob = "cycle"
	} else if operation != "pause" && operation != "resume" {
		return OperationResult{}, errors.New("ordinary hosted controller operation must be cycle, pause, or resume")
	}
	if !exactSHA.MatchString(strings.ToLower(strings.TrimSpace(expectedHeadSHA))) {
		return OperationResult{}, errors.New("ordinary hosted controller operation requires an exact default-branch head")
	}
	return waitForExactOperation(ctx, client, config, operation, requestID, "", expectedJob, strings.ToLower(expectedHeadSHA), issuedAt)
}

// WaitForReadOperation waits for the exact status-job receipt generated by a
// public hosted status or doctor request. It never substitutes the latest
// unrelated controller run.
func WaitForReadOperation(ctx context.Context, client *gh.Client, config integrated.Config, operation, requestID, expectedHeadSHA string, issuedAt time.Time) (OperationResult, error) {
	if operation != "status" && operation != "doctor" {
		return OperationResult{}, errors.New("hosted read operation must be status or doctor")
	}
	if !exactSHA.MatchString(strings.ToLower(strings.TrimSpace(expectedHeadSHA))) {
		return OperationResult{}, errors.New("hosted read operation requires an exact default-branch head")
	}
	return waitForExactOperation(ctx, client, config, operation, requestID, "", "status", strings.ToLower(expectedHeadSHA), issuedAt)
}

func waitForExactOperation(ctx context.Context, client *gh.Client, config integrated.Config, operation, requestID, requestSHA256, expectedJob, expectedHeadSHA string, issuedAt time.Time) (OperationResult, error) {
	var result OperationResult
	operatorOperation := hostedOperatorReceiptOperation(operation)
	if client == nil || !controllerRequestID.MatchString(requestID) || expectedJob != "cycle" && expectedJob != "control" && expectedJob != "status" ||
		operatorOperation && (expectedJob != "control" || !hostedDigestPattern.MatchString(requestSHA256)) ||
		!operatorOperation && requestSHA256 != "" || expectedJob == "status" && operation != "status" && operation != "doctor" || issuedAt.IsZero() {
		return result, errors.New("hosted operation wait requires an exact client, request identity, digest, and issue time")
	}
	owner, repository, err := splitRepository(config.Repository)
	if err != nil {
		return result, err
	}
	wantTitle := "Hive " + operation + " " + requestID
	ticker := time.NewTicker(4 * time.Second)
	defer ticker.Stop()
	for {
		found, pending, inspectErr := inspectRequestedOperation(ctx, client, owner, repository, config, operation, requestID, requestSHA256, expectedJob, expectedHeadSHA, wantTitle, issuedAt)
		if inspectErr != nil {
			return result, inspectErr
		}
		if found != nil {
			return *found, nil
		}
		if !pending && time.Since(issuedAt) > 2*time.Minute {
			return result, ErrOperationRunNotFound
		}
		select {
		case <-ctx.Done():
			return result, fmt.Errorf("wait for hosted operation result: %w", ctx.Err())
		case <-ticker.C:
		}
	}
}

func inspectRequestedOperation(ctx context.Context, client *gh.Client, owner, repository string, config integrated.Config, operation, requestID, requestSHA256, expectedJob, expectedHeadSHA, title string, issuedAt time.Time) (*OperationResult, bool, error) {
	pending := false
	for _, status := range []string{"requested", "waiting", "pending", "queued", "in_progress", "completed"} {
		for page := 1; page <= 5; page++ {
			runs, response, err := client.Actions.ListWorkflowRunsByFileName(ctx, owner, repository, integrated.HostedControllerWorkflowPath, &gh.ListWorkflowRunsOptions{
				Branch: config.DefaultBranch, Status: status, ExcludePullRequests: true, ListOptions: gh.ListOptions{Page: page, PerPage: 100},
			})
			if err != nil {
				return nil, false, fmt.Errorf("list %s hosted operation runs: %w", status, err)
			}
			if runs == nil {
				return nil, false, errors.New("hosted operation run inventory is empty")
			}
			candidates := append([]*gh.WorkflowRun(nil), runs.WorkflowRuns...)
			sort.Slice(candidates, func(i, j int) bool { return candidates[i].GetID() > candidates[j].GetID() })
			for _, run := range candidates {
				if run == nil || run.GetDisplayTitle() != title || run.GetCreatedAt().Time.Before(issuedAt.Add(-time.Minute)) {
					continue
				}
				if status != "completed" {
					pending = true
					continue
				}
				evidence, err := validateRun(run, config, "completed")
				if err != nil {
					return nil, false, err
				}
				job, conclusion, err := inspectControllerResultJob(ctx, client, owner, repository, run)
				if err != nil {
					return nil, false, err
				}
				if job != expectedJob {
					return nil, false, fmt.Errorf("hosted operation executed in unexpected job %q", job)
				}
				artifact, err := findControllerArtifact(ctx, client, owner, repository, config, evidence, job)
				if err != nil {
					if pending {
						continue
					}
					return nil, false, fmt.Errorf("%w: run %d (%s): %v", ErrOperationRunTerminatedWithoutReceipt, evidence.ID, conclusion, err)
				}
				receipt, err := downloadControllerReceipt(ctx, client, owner, repository, artifact, evidence, job)
				if err != nil {
					if pending {
						continue
					}
					return nil, false, fmt.Errorf("%w: run %d (%s): %v", ErrOperationRunTerminatedWithoutReceipt, evidence.ID, conclusion, err)
				}
				_, stateHead, err := inspectStateBranch(ctx, client, owner, repository, config.HostedStateBranch)
				if err != nil {
					return nil, false, err
				}
				if err := validateRequestedOperationReceipt(ctx, client, owner, repository, receipt, config, evidence, job, stateHead, operation, requestID, requestSHA256, expectedHeadSHA); err != nil {
					return nil, false, err
				}
				return &OperationResult{StateReceiptEvidence: StateReceiptEvidence{
					Run: evidence, Job: job, ArtifactID: artifact.GetID(), ArtifactName: artifact.GetName(), Operation: receipt.Operation,
					RequestID: receipt.RequestID, RequestSHA256: receipt.RequestSHA256, StateBefore: receipt.StateBefore, StateAfter: receipt.StateAfter,
					Sequence: receipt.Sequence, Paused: *receipt.Paused, Release: receipt.Release, Actor: receipt.Actor, RunResult: receipt.Run,
					DoctorResult: receipt.Doctor, StatusResult: receipt.Status, OperatorResult: receipt.Operator,
					OperatorStatus: receipt.OperatorStatus, OperatorTerminalSHA256: receipt.OperatorTerminalSHA256,
					OperatorLedgerSequence: receipt.OperatorLedgerSequence, OperatorReplayed: receipt.OperatorReplayed,
				}, Conclusion: conclusion, Error: receipt.Error}, false, nil
			}
			if response == nil || response.NextPage == 0 || len(candidates) == 0 || candidates[len(candidates)-1].GetCreatedAt().Time.Before(issuedAt.Add(-time.Minute)) {
				break
			}
			if page == 5 {
				return nil, false, errors.New("hosted operation run discovery exceeded its strict five-page bound")
			}
		}
	}
	return nil, pending, nil
}

func inspectControllerResultJob(ctx context.Context, client *gh.Client, owner, repository string, run *gh.WorkflowRun) (string, string, error) {
	jobs, response, err := client.Actions.ListWorkflowJobs(ctx, owner, repository, run.GetID(), &gh.ListWorkflowJobsOptions{Filter: "latest", ListOptions: gh.ListOptions{PerPage: 10}})
	if err != nil {
		return "", "", fmt.Errorf("inspect hosted operation jobs: %w", err)
	}
	if jobs == nil || jobs.GetTotalCount() != 3 || len(jobs.Jobs) != 3 || response != nil && response.NextPage != 0 {
		return "", "", errors.New("hosted operation run has an incomplete or unexpected job inventory")
	}
	expected := map[string]bool{"cycle": false, "control": false, "status": false}
	executed, conclusion := "", ""
	for _, job := range jobs.Jobs {
		name := job.GetName()
		if _, ok := expected[name]; !ok || expected[name] || job.GetStatus() != "completed" {
			return "", "", errors.New("hosted operation job inventory contains an unexpected, duplicate, or incomplete job")
		}
		expected[name] = true
		if job.GetConclusion() == "skipped" {
			continue
		}
		if executed != "" || !hostedOperationTerminalConclusion(job.GetConclusion()) {
			return "", "", errors.New("hosted operation run does not have exactly one terminal operation job")
		}
		executed, conclusion = name, job.GetConclusion()
	}
	if executed == "" {
		return "", "", errors.New("hosted operation run has no terminal operation job")
	}
	return executed, conclusion, nil
}

func hostedOperationTerminalConclusion(value string) bool {
	switch value {
	case "success", "failure", "cancelled", "timed_out", "action_required", "startup_failure", "stale":
		return true
	default:
		return false
	}
}

func validateRequestedOperationReceipt(ctx context.Context, client *gh.Client, owner, repository string, receipt controllerReceipt, config integrated.Config, run RunEvidence, job, stateHead, operation, requestID, requestSHA256, expectedHeadSHA string) error {
	if receipt.SchemaVersion != "hive.hosted-cycle.v1" || receipt.Repository != config.Repository || receipt.StateBranch != config.HostedStateBranch || receipt.Paused == nil ||
		receipt.Operation != operation || receipt.RequestID != requestID {
		return errors.New("hosted operation receipt does not match its exact schema, repository, operation, or request")
	}
	if !receiptMatchesHostedRelease(receipt.Release, config) {
		return errors.New("hosted operation receipt does not match the exact immutable hosted release")
	}
	if !exactSHA.MatchString(receipt.StateBefore) || !exactSHA.MatchString(receipt.StateAfter) || receipt.Sequence == 0 {
		return errors.New("hosted operation receipt is not bound to exact state commits")
	}
	if run.Event != "workflow_dispatch" || run.RunAttempt != 1 || run.DisplayTitle != "Hive "+operation+" "+requestID ||
		expectedHeadSHA != "" && run.HeadSHA != expectedHeadSHA {
		return errors.New("hosted operation receipt workflow identity is invalid")
	}
	if job == "status" {
		if requestSHA256 != "" || receipt.RequestSHA256 != "" || receipt.Actor != nil || len(receipt.Operator) != 0 || receipt.OperatorStatus != "" ||
			receipt.OperatorTerminalSHA256 != "" || receipt.OperatorLedgerSequence != 0 || receipt.OperatorReplayed || receipt.StateBefore != receipt.StateAfter || receipt.StateAfter != stateHead {
			return errors.New("hosted read receipt contains authority fields, changed state, or is stale")
		}
		if receipt.Error == "" && operation == "status" && len(receipt.Status) == 0 || receipt.Error == "" && operation == "doctor" && len(receipt.Doctor) == 0 {
			return errors.New("successful hosted read receipt lacks its exact typed result")
		}
		return nil
	}
	if !hostedOperatorReceiptOperation(operation) {
		allowed := job == "cycle" && operation == "cycle" || job == "control" && (operation == "pause" || operation == "resume")
		if !allowed || requestSHA256 != "" || receipt.RequestSHA256 != "" || receipt.Actor != nil || len(receipt.Operator) != 0 ||
			receipt.OperatorStatus != "" || receipt.OperatorTerminalSHA256 != "" || receipt.OperatorLedgerSequence != 0 || receipt.OperatorReplayed {
			return errors.New("ordinary hosted controller receipt contains an invalid job or operator authority")
		}
		if operation == "pause" && !*receipt.Paused || operation == "resume" && *receipt.Paused {
			return errors.New("ordinary hosted controller receipt does not prove the requested pause state")
		}
		if receipt.StateAfter != stateHead {
			comparison, _, err := client.Repositories.CompareCommits(ctx, owner, repository, receipt.StateAfter, stateHead, nil)
			if err != nil || !strings.EqualFold(comparison.GetStatus(), "ahead") || comparison.GetBehindBy() != 0 {
				return errors.New("ordinary hosted controller result state is not an authenticated ancestor of the current state branch")
			}
		}
		return nil
	}
	if job != "control" || receipt.RequestSHA256 != requestSHA256 || receipt.Actor == nil || receipt.Actor.ID <= 0 || strings.TrimSpace(receipt.Actor.Login) == "" {
		return errors.New("hosted operator receipt does not match its exact digest, human actor, or control job")
	}
	if run.ActorID != receipt.Actor.ID || run.TriggeringActorID != receipt.Actor.ID || !strings.EqualFold(run.ActorLogin, receipt.Actor.Login) ||
		!strings.EqualFold(run.TriggeringActorLogin, receipt.Actor.Login) || !strings.EqualFold(run.ActorType, "User") || !strings.EqualFold(run.TriggeringActorType, "User") {
		return errors.New("hosted operation receipt actor does not match the immutable workflow run actor")
	}
	if err := validateHostedOperatorTerminalReceipt(receipt); err != nil {
		return err
	}
	if receipt.StateAfter != stateHead {
		comparison, _, err := client.Repositories.CompareCommits(ctx, owner, repository, receipt.StateAfter, stateHead, nil)
		if err != nil || !strings.EqualFold(comparison.GetStatus(), "ahead") || comparison.GetBehindBy() != 0 {
			return errors.New("hosted operation result state is not an authenticated ancestor of the current state branch")
		}
	}
	return nil
}

func hostedOperatorReceiptOperation(operation string) bool {
	return strings.HasPrefix(operation, "approve-") || operation == "retry-repair" || strings.HasPrefix(operation, "recover-dispatch-")
}
