package profiles

import (
	"fmt"
	"os"
	"strings"
)

// ownedKeys are the contributor.env keys this package generates from
// profiles.yml. Every other key in an existing contributor.env (for example
// HIVE_LITELLM_ENDPOINT) is preserved verbatim by Project.
var ownedKeys = map[string]bool{
	"HIVE_HUB":                true,
	"HIVE_REGISTRATION_TOKEN": true,
	"CONTRIBUTOR_ID":          true,
	"CONTRIBUTOR_USERNAME":    true,
	"AGENT_BACKEND":           true,
	"HIVE_SESSION":            true,
}

// Project regenerates contributor.env from the profiles file. The active
// profile is emitted FIRST in each positional list: bin/contributor-relay.js
// starts soliciting at activeHubIndex 0, so `hives use` takes effect on the
// next relay start (phase 1 of hivecommons/hive#8097; a live switch without a
// restart is phase 2).
//
// The three lists are generated from the same loop over the same slice, so
// they can never disagree in length — the relay's "FATAL: HIVE_HUB lists N
// hub(s)" path is unreachable from a file this function wrote.
func Project(dir string, f *File) error {
	if len(f.Profiles) == 0 {
		return fmt.Errorf("no profiles to project; add one with 'hivectl hives add'")
	}
	active := f.ActiveProfile()
	ordered := make([]*Profile, 0, len(f.Profiles))
	ordered = append(ordered, active)
	for i := range f.Profiles {
		if p := &f.Profiles[i]; p != active {
			ordered = append(ordered, p)
		}
	}
	hubs := make([]string, len(ordered))
	tokens := make([]string, len(ordered))
	ids := make([]string, len(ordered))
	for i, p := range ordered {
		hubs[i] = p.Hub
		tokens[i] = p.RegistrationToken
		ids[i] = p.ContributorID
	}

	var b strings.Builder
	b.WriteString("# Generated by hivectl hives from " + FileName + " — edit profiles, not this file.\n")
	fmt.Fprintf(&b, "HIVE_REGISTRATION_TOKEN=%s\n", strings.Join(tokens, ","))
	fmt.Fprintf(&b, "HIVE_HUB=%s\n", strings.Join(hubs, ","))
	fmt.Fprintf(&b, "CONTRIBUTOR_ID=%s\n", strings.Join(ids, ","))
	if f.Username != "" {
		fmt.Fprintf(&b, "CONTRIBUTOR_USERNAME=%s\n", f.Username)
	}
	if active.Backend != "" {
		fmt.Fprintf(&b, "AGENT_BACKEND=%s\n", active.Backend)
	}
	if active.Session != "" {
		fmt.Fprintf(&b, "HIVE_SESSION=%s\n", active.Session)
	}

	// Preserve keys the projection does not own, in their original order.
	if prev, err := parseEnvFile(EnvPath(dir)); err == nil {
		for _, key := range prev.order {
			if !ownedKeys[key] {
				fmt.Fprintf(&b, "%s=%s\n", key, prev.values[key])
			}
		}
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, EnvFileName+".tmp-*")
	if err != nil {
		return fmt.Errorf("writing %s: %w", EnvPath(dir), err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	// 0600 before content: the registration token is a live bearer credential.
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return fmt.Errorf("securing %s: %w", tmpName, err)
	}
	if _, err := tmp.WriteString(b.String()); err != nil {
		tmp.Close()
		return fmt.Errorf("writing %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("writing %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, EnvPath(dir)); err != nil {
		return fmt.Errorf("replacing %s: %w", EnvPath(dir), err)
	}
	return nil
}
