package github

import (
	"crypto/tls"
	"crypto/x509"
	"net/http"
	"os"
	"sync"
	"time"

	gh "github.com/google/go-github/v72/github"
)

// mintClientTimeout bounds a single App-JWT / installation-token HTTP call.
// These are point calls to GitHub (or the MITM proxy in front of it); a stuck
// dial must not pin the token-refresh path indefinitely. Matches the 30s used
// by the App client transport in NewClientFromApp.
const mintClientTimeout = 30 * time.Second

// The chicken-and-egg this file breaks
// ------------------------------------
// When F5 forced egress is on, every outbound :443 (including this package's
// GitHub App token-mint calls to POST /app/installations/{id}/access_tokens) is
// iptables-REDIRECTed to the in-process MITM proxy, which presents a leaf cert
// forged by the proxy's own CA at /data/proxy-ca.pem. Go's crypto/x509 must
// trust that CA or every mint fails "x509: certificate signed by unknown
// authority" → "all N repos failed" → the agent loop is dead.
//
// The proxy CA is GENERATED BY the Go proxy at runtime (proxy.NewGitHubProxy →
// loadOrGenerateCA writes /data/proxy-ca.pem). On a fresh-PVC boot that file
// does NOT exist yet when the process starts, so:
//
//   - The entrypoint's SSL_CERT_FILE combined-bundle build (#2686) is gated on
//     `[ -f /data/proxy-ca.pem ]`, which is FALSE on first boot → SSL_CERT_FILE
//     is never exported → the Go process falls back to the system trust store.
//   - The system store's own CA-install (gosu update-ca-certificates) also runs
//     AFTER launch and can fail, leaving a multi-minute window after every pod
//     roll where token minting fails until the system CA eventually settles.
//
// Fix (Option B, race-free): the very process that GENERATES the proxy CA also
// establishes the trust for it. Instead of depending on an env var set by the
// entrypoint before launch, the token-mint HTTP client below carries its own
// RootCAs pool = system roots + the proxy CA, and it LAZILY (re)loads the proxy
// CA from disk whenever the file appears or changes. So the first mint after
// the proxy has written /data/proxy-ca.pem trusts it immediately — no
// dependency on entrypoint ordering, no cached-empty-pool window.
//
// The pool always includes the SYSTEM roots too, so advisory mode (no forced
// egress: the mint reaches api.github.com directly with a real public cert)
// keeps working. This is the same "trust BOTH public roots AND proxy CA"
// safety the entrypoint's combined bundle provides.

// proxyCAPath is the PVC location of the MITM CA cert the in-process proxy
// generates (must match proxy.CACertPath). A var so tests can redirect it.
var proxyCAPath = "/data/proxy-ca.pem"

// proxyCAReloadInterval bounds how often the disk is stat/re-read. Minting is
// infrequent (a token lasts ~1h and is refreshed within a 20m buffer), so a
// short interval costs nothing and lets a freshly-written CA be picked up
// promptly on first boot without a per-call read.
const proxyCAReloadInterval = 5 * time.Second

// proxyTrustPool builds and caches a RootCAs pool of (system roots + proxy CA),
// reloading the proxy CA from disk when the file changes so a CA written after
// process start (the fresh-PVC boot case) is trusted on the next mint.
type proxyTrustPool struct {
	mu         sync.Mutex
	pool       *x509.CertPool
	caModTime  time.Time
	caSize     int64
	lastReload time.Time

	// transport is the process-wide shared HTTP transport for every
	// JWT/token-mint client, rebuilt only when the RootCAs pool itself is
	// rebuilt. transportPool records which pool the cached transport carries
	// so a pool rebuild (CA appearing/rotating) invalidates it. See
	// sharedTransport for why sharing (rather than a transport per call) is
	// load-bearing and not merely an optimization (#3875).
	transport     *http.Transport
	transportPool *x509.CertPool
}

// certPool returns a RootCAs pool trusting the system roots plus the proxy CA
// if present. It re-reads /data/proxy-ca.pem at most once per
// proxyCAReloadInterval, and only rebuilds the pool when the file's
// size/mtime changed, so the steady-state cost is a single stat.
//
// A nil return means "use Go's default (system) trust" — callers pass it
// straight into tls.Config.RootCAs, where nil already means system roots, so
// the system-roots path is never broken even if reading the CA fails.
func (t *proxyTrustPool) certPool() *x509.CertPool {
	t.mu.Lock()
	defer t.mu.Unlock()

	now := time.Now()
	if t.pool != nil && now.Sub(t.lastReload) < proxyCAReloadInterval {
		return t.pool
	}
	t.lastReload = now

	info, err := os.Stat(proxyCAPath)
	if err != nil {
		// No proxy CA on disk yet (fresh boot, before the proxy generated it,
		// or advisory mode where it may never exist). Fall back to system roots
		// only. Returning the previously-built pool (if any) would also be
		// correct, but system-only is the honest state until the CA appears.
		if t.pool != nil {
			// Keep a previously-built (system + CA) pool if the file merely
			// became briefly unreadable; do not downgrade an established trust.
			return t.pool
		}
		// Cache the system-only fallback so callers see a STABLE pool pointer
		// while the CA is absent — sharedTransport keys transport reuse on
		// pool identity, and a fresh clone per call would rebuild the
		// transport (and drop its keep-alive pool) on every advisory-mode
		// mint. The stat-succeeds path above still rebuilds the moment the CA
		// file appears, because caModTime/caSize have never been recorded for
		// it.
		t.pool = systemOnlyPool()
		return t.pool
	}

	// Rebuild only when the file actually changed since we last loaded it.
	if t.pool != nil && info.ModTime().Equal(t.caModTime) && info.Size() == t.caSize {
		return t.pool
	}

	caPEM, err := os.ReadFile(proxyCAPath)
	if err != nil {
		if t.pool != nil {
			return t.pool
		}
		return systemOnlyPool()
	}

	pool := systemOnlyPool()
	if pool == nil {
		pool = x509.NewCertPool()
	}
	if !pool.AppendCertsFromPEM(caPEM) {
		// Unparseable CA file: keep whatever trust we already had rather than
		// serving an empty/partial pool.
		if t.pool != nil {
			return t.pool
		}
		return systemOnlyPool()
	}

	t.pool = pool
	t.caModTime = info.ModTime()
	t.caSize = info.Size()
	return t.pool
}

// systemOnlyPool returns a clone of the system cert pool, or nil (which
// tls.Config treats as "system roots") when the system pool is unavailable.
func systemOnlyPool() *x509.CertPool {
	if pool, err := x509.SystemCertPool(); err == nil {
		return pool
	}
	return nil
}

// sharedProxyTrust is the process-wide pool used by every JWT/token-mint client
// so the reload bookkeeping (and the system-pool load) is shared, not repeated
// per call.
var sharedProxyTrust = &proxyTrustPool{}

// sharedTransport returns the process-wide *http.Transport carrying the
// current (system roots + proxy CA) pool, building a new one only when the
// pool itself has been rebuilt (the CA appearing on first boot, or rotating).
// The superseded transport gets CloseIdleConnections so its pooled sockets are
// reclaimed immediately instead of lingering until the peer or the idle reaper
// gets around to them.
//
// Sharing ONE transport across mint calls is load-bearing, not an
// optimization (#3875): the previous shape — a freshly cloned Transport per
// call — meant every mint/token call dialed a brand-new connection and then
// orphaned it in a single-use idle pool that no future call could ever reuse
// and nothing ever explicitly closed. Under a retry loop against a slow
// GitHub, that manufactured sockets at the exact moment the process could
// least afford them. With a shared transport, keep-alive reuse actually
// happens, and Go's idle-pool accounting (IdleConnTimeout, per-host caps,
// inherited from http.DefaultTransport) governs one pool instead of one pool
// per historical call.
//
// crypto/tls has no per-handshake roots hook, so the pool is captured at
// transport construction; certPool()'s own reload interval keeps it fresh, and
// a CA that appears after process start yields a new pool pointer — which is
// exactly the signal used here to rebuild the transport for the next mint.
func (t *proxyTrustPool) sharedTransport() *http.Transport {
	pool := t.certPool()

	t.mu.Lock()
	defer t.mu.Unlock()
	if t.transport != nil && t.transportPool == pool {
		return t.transport
	}

	var transport *http.Transport
	if base, ok := http.DefaultTransport.(*http.Transport); ok {
		transport = base.Clone()
	} else {
		transport = &http.Transport{}
	}
	if transport.TLSClientConfig == nil {
		transport.TLSClientConfig = &tls.Config{}
	} else {
		transport.TLSClientConfig = transport.TLSClientConfig.Clone()
	}
	// pool is (system roots + proxy CA), or a system-only pool while the CA
	// does not yet exist. nil also means "system roots" to crypto/tls, so the
	// direct-HTTPS (advisory mode) path is never broken.
	transport.TLSClientConfig.RootCAs = pool

	if old := t.transport; old != nil {
		old.CloseIdleConnections()
	}
	t.transport = transport
	t.transportPool = pool
	return transport
}

// proxyTrustingHTTPClient returns an *http.Client whose TLS RootCAs trust the
// system roots plus the in-process proxy CA (lazily reloaded from disk). This
// is the client the App-JWT / installation-token mint calls use so a fresh-PVC
// boot trusts the proxy CA from the FIRST mint attempt, independent of
// SSL_CERT_FILE or the entrypoint's launch ordering.
//
// The client wrapper is per-call (it only carries the timeout); the transport
// underneath — the part that owns sockets — is shared and reaped, see
// sharedTransport.
func proxyTrustingHTTPClient(timeout time.Duration) *http.Client {
	return &http.Client{Transport: sharedProxyTrust.sharedTransport(), Timeout: timeout}
}

// newJWTClient builds a go-github client authenticated with an App JWT whose
// HTTP transport trusts the proxy CA (see proxyTrustingHTTPClient). Every
// App-JWT / installation-token call must use this rather than gh.NewClient(nil)
// so the mint verifies the MITM proxy's forged cert on a fresh-PVC boot.
func newJWTClient(jwtToken, apiURL string) *gh.Client {
	client := gh.NewClient(proxyTrustingHTTPClient(mintClientTimeout)).WithAuthToken(jwtToken)
	setBaseURL(client, apiURL)
	return client
}

// newTokenClient builds a go-github client authenticated with an installation
// token whose HTTP transport trusts the proxy CA. Used by NewClient so ordinary
// API traffic (which is also proxied under forced egress) verifies correctly.
func newTokenClient(token, apiURL string) *gh.Client {
	client := gh.NewClient(proxyTrustingHTTPClient(mintClientTimeout)).WithAuthToken(token)
	setBaseURL(client, apiURL)
	return client
}
