name: Add Help Wanted Label

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  label:
    uses: hivecommons/infra/.github/workflows/reusable-add-help-wanted.yml@f1c0b61675386f54e63c04cf07b3aa933cc963eb # hivecommons/infra main as of 2026-09-02
