name: Copilot DCO

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  copilot-dco:
    uses: hivecommons/infra/.github/workflows/reusable-copilot-dco.yml@f1c0b61675386f54e63c04cf07b3aa933cc963eb # hivecommons/infra main as of 2026-09-02
