name: Greetings

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  greet:
    uses: hivecommons/infra/.github/workflows/reusable-greetings.yml@f1c0b61675386f54e63c04cf07b3aa933cc963eb # hivecommons/infra main as of 2026-09-02
