name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [ "main", "v4" ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  analysis:
    uses: hivecommons/infra/.github/workflows/reusable-scorecard.yml@f1c0b61675386f54e63c04cf07b3aa933cc963eb # hivecommons/infra main as of 2026-09-02
